create service.yml

apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
